openapi: 3.0.0
info:
  title: PSI Powierzenia - szablony
  description: Detailed description can be found in the repository.
  version: 0.1.0
servers:
  - url: https://localhost/
    description: Main (production) server
  - url: http://localhost:3000
    description: Local server for development
paths:
  /templates/{id}:
    get:
      summary: Get template by id.
      description: Optional extended description in CommonMark or HTML.
      operationId: getTemplate
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Template
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
  /templates:
    get:
      summary: List templates.
      description: Optional extended description in CommonMark or HTML.
      operationId: listTemplates
      responses:
        '200':
          description: Template
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TemplateList'
components:
  schemas:
    TemplateList:
      type: array
      items:
        $ref: '#/components/schemas/Template'
    Template:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/TemplateId'
        faculty:
          $ref: '#/components/schemas/Faculty'
        study:
          $ref: '#/components/schemas/Study'
        message:
          $ref: '#/components/schemas/Message'
    TemplateId:
      type: string
    Faculty:
      description: wydział
      type: string
    Study:
      description: kierunek
      type: string
    Message:
      type: string
