openapi: 3.0.0
info:
  title: PSI Powierzenia - powerzenia
  description: Detailed description can be found in the repository.
  version: 0.1.0
servers:
  - url: https://localhost/
    description: Main (production) server
  - url: http://localhost:3000
    description: Local server for development
  - url: http://localhost:6006
    description: Local server for Storybook
paths:
  /entrustments:
    post:
      summary: Find entrustments.
      description: Optional extended description in CommonMark or HTML.
      operationId: findEntrustments
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntrustmentFind'
      responses:
        '200':
          description: Template
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntrustmentFindResponse'
components:
  schemas:
    EntrustmentFind:
      type: object
      properties:
        year:
          $ref: '#/components/schemas/Year'
        faculty:
          $ref: '#/components/schemas/Faculty'
        study:
          $ref: '#/components/schemas/Study'
    EntrustmentFindResponse:
      type: object
      properties:
        entrustments:
          type: array
          items:
            $ref: '#/components/schemas/Entrustment'
        courses:
          type: array
          items:
            $ref: '#/components/schemas/Course'
        lecturers:
          type: array
          items:
            $ref: '#/components/schemas/Lecturer'
        preferences:
          type: array
          items:
            $ref: '#/components/schemas/Preference'
        limitations:
          type: array
          items:
            $ref: '#/components/schemas/Limitation'
        pastAssignments:
          type: array
          items:
            $ref: '#/components/schemas/Assignment'
    Entrustment:
      type: object
      properties:
        entrustmentId:
          $ref: '#/components/schemas/EntrustmentId'
        lecturerId:
          $ref: '#/components/schemas/LecturerId'
        courseId:
          $ref: '#/components/schemas/CourseId'
        hours:
          $ref: '#/components/schemas/Hours'
    Course:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/CourseId'
    Lecturer:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/LecturerId'
        pensum:
          $ref: '#/components/schemas/Pensum'
    Preference:
      type: object
      properties:
        lecturerId:
          $ref: '#/components/schemas/LecturerId'
        courseId:
          $ref: '#/components/schemas/CourseId'
    Limitation:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/LimitationId'
    Assignment:
      type: object
      properties:
        lecturerId:
          $ref: '#/components/schemas/LecturerId'
        courseId:
          $ref: '#/components/schemas/CourseId'
    EntrustmentId:
      type: string
    LecturerId:
      type: string
    CourseId:
      type: string
    LimitationId:
      type: string
    Year:
      type: string
    Faculty:
      type: string
    Study:
      type: string
    Hours:
      type: integer
    Pensum:
      type: integer
