openapi: 3.0.0
info:
  title: PIISW Order App - Order
  description: Detailed description can be found in the repository.
  version: 0.1.0
servers:
  - url: https://piisw-order-app.herokuapp.com/
    description: Main (production) server
  - url: http://localhost:3000
    description: Local server for development
  - url: http://localhost:6006
    description: Local server for Storybook
paths:
  /orders/{id}:
    get:
      summary: Get order by id.
      description: Optional extended description in CommonMark or HTML.
      operationId: getOrder
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
  /orders/{id}/deliver:
    post:
      summary: Deliver order by id.
      description: Optional extended description in CommonMark or HTML.
      operationId: deliverOrder
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Order delivered.
  /orders:
    get:
      summary: List orders.
      description: Optional extended description in CommonMark or HTML.
      operationId: listOrders
      responses:
        '200':
          description: Order status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderList'
    post:
      summary: Creates a new order.
      description: Optional extended description in CommonMark or HTML.
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Order status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
    put:
      summary: Replaces the order.
      description: Optional extended description in CommonMark or HTML.
      operationId: replaceOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Order status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
  /orders/install:
    get:
      summary: Refresh orders in the database.
      description: Order list contains orders.
      operationId: installOrders
      responses:
        '204':
          description: Refresh complete.
components:
  schemas:
    OrderList:
      type: array
      items:
        $ref: '#/components/schemas/Order'
    Order:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/OrderId'
        takeout:
          type: boolean
        status:
          $ref: '#/components/schemas/OrderStatus'
        items:
          $ref: '#/components/schemas/OrderItemList'
    OrderId:
      type: string
    OrderItemList:
      type: array
      items:
        $ref: '#/components/schemas/OrderItem'
    OrderItem:
      type: object
      properties:
        id:
          $ref: '../../../../product/src/main/openapi/api.yaml#/components/schemas/ProductId'
        count:
          description: Unit count
          type: integer
        price:
          description: Unit price
          type: number
    OrderStatus:
      description: >
        ### Statuses
        * CREATED the default status of new orders
        * INPROGRESS indicates the order is accepted
        * DELIVERED when the order is received
      type: string
      enum:
        - CREATED
        - INPROGRESS
        - DELIVERED
